### PR TITLE
fix(migration): UX improvements to renku version

### LINKED ISSUE #1233: Project status / update UI improvements
# Description

The project status / update UI needs to be made more robust and better handle all the cases.

# Implementation

Pre-req: Improve the information returned by the `check_migrations` endpoint. See https://github.com/swissdatasciencecenter/renku-python/issues/2048.

The new information should be structured like:
```
{
	"result": {
		"project_supported": true,
                 "core_renku_version": "0.14.2",
                "project_renku_version": "0.14.0", //latest version of renku used by a user on the project
		"core_compatibility_status": {
			"project_metadata_version": "7",
                        "current_metadata_version": "7"
			"migration_required": false,
		},
		"dockerfile_renku_status": {
			"newer_renku_available": true,      // docker_update_possible -> newer_renku_available
			"automated_dockerfile_update": true,  // new field
			"latest_renku_version": "0.14.2",
			"dockerfile_renku_version": "0.14.0",
		},
		"template_status": {
			"automated_template_update": false,
			"newer_template_available": true,    // template_update_possible -> newer_template_available
			"template_source": "https://github.com/SwissDataScienceCenter/renku-project-template",
			"project_template_version": "73db625bf5d9effa1d76a4e5e1fcbcb1a927f654",  // current_template_version -> project_template_version (ideally semver)
			"latest_template_version": "817b03c0f434a79eb54473688c1f897a66228b3d",		
			"template_ref": "master",
			"template_id": "python-minimal"
		}
	}
}
```

Given that information, the UI should be restructured a bit. Currently we have two sections: `Renku Version` and `Template Version` (ignoring KG version, which is fine as is). This should become 3 sections.

### RenkuLab UI Compatibility

```
if (core_compatibility_status.migration_required) {
	show
		Datasets can be created and modified from the RenkuLab UI.
} else {
	show
		Datasets cannot be created and modified from the RenkuLab UI. Please upgrade the project to take advantage of these UI features.
}
```

### Renku Version

```
if (!dockerfile_renku_status.newer_renku_available) {
	show 
		Project version ${dockerfile_renku_status.project_version}
		This project is using the latest version of renku.
} else {
	show 
		Project version ${dockerfile_renku_status.project_version}
		Latest version ${dockerfile_renku_status.latest_version}
		A newer version of Renku is available. See the [release notes] to learn more about improvements and new features.
		
	if (core_compatibility_status.migration_required) {
		An upgrade is required to create and modify datasets from the RenkuLab UI.
	}
	
	if (dockerfile_renku_status.automated_dockerfile_update) {
		[Update] [Do you prefer manual instructions?]
	} else {
		The Renku version cannot be automatically updated. (manual instructions)
	}
}
```

### Project Template

```
if (template_status.template_id == null) {
	show
		This project does not use a versioned template.
} else {
	show 
		Template id ${template_status.template_id}
		Template ref ${template_status.template_ref}
		Template source <a href={template_status.template_source}>{template_status.template_source}</a>
		
	if (template_status.newer_template_available) {
		A newer version of this template is available. Please see the <a href={template_status.template_source}>template source</a> to 
		learn more about the changes to the template.
		
		if (template_status.automated_template_update) {
			[Update] [Do you prefer manual instructions?]
		} else {
			The template version cannot be automatically updated. (manual instructions)
		}		
	}
}
```

# Table
|    |                                                                                                 | MIGRATION STATUS                   | ACTION/MESSAGE                                                               |
|----|-------------------------------------------------------------------------------------------------|------------------------------------|------------------------------------------------------------------------------|
| 1  | migration_required T project_supported T newer_renku_available T automated_dockerfile_update T  | NEEDED                             | AUTOMATIC MIGRATION (DOCKER + METADATA)                                      |
| 2  | migration_required T project_supported T newer_renku_available T automated_dockerfile_update F  | NEEDED                             | MANUAL UPGRADE                        |
| 3  | migration_required T project_supported T newer_renku_available F automated_dockerfile_update T  | NEEDED   | AUTOMATIC METADATA MIGRATION + DOCKERFILE UP TO DATE                         |
| 4  | migration_required T project_supported T newer_renku_available F automated_dockerfile_update F  | NEEDED    | AUTOMATIC METADATA MIGRATION + DOCKERFILE UP TO DATE                         |
| 5  | migration_required T project_supported F newer_renku_available T automated_dockerfile_update T  | NOT POSSIBLE                             | MANUAL METADATA MIGRATION + AUTOMATIC DOCKERFILE UPGRADE                     |
| 6  | migration_required T project_supported F newer_renku_available T automated_dockerfile_update F  | NOT POSSIBLE                             | MANUAL METADATA AND DOCKERFILE UPGRADE                                       |
| 7  | migration_required T project_supported F newer_renku_available F automated_dockerfile_update T  | NOT POSSIBLE     | MANUAL METADATA MIGRATION + DOCKERFILE UP TO DATE                            |
| 8  | migration_required T project_supported F newer_renku_available F automated_dockerfile_update F  | NEEDED                             | MANUAL METADATA MIGRATION + DOCKERFILE IN UNKNOWN STATE                            |
| 9  | migration_required F project_supported T newer_renku_available T automated_dockerfile_update T  | OPTIONAL                         | METADATA UP TO DATE + AUTOMATIC DOCKERFILE UPDATE                            |
| 10 | migration_required F project_supported T newer_renku_available T automated_dockerfile_update F  | OPTIONAL                         | METADATA UP TO DATE + MANUAL DOCKERFILE UPGRADE                              |
| 11 | migration_required F project_supported T newer_renku_available F automated_dockerfile_update T  | NO NEED                            | METADATA UP TO DATE + DOCKERFILE UP TO DATE                                  |
| 12 | migration_required F project_supported T newer_renku_available F automated_dockerfile_update F  | NO NEED   | METADATA UP TO DATE + DOCKERFILE UNKNOWN SINCE IT’S NOT COMPATIBLE           |
| 13 | migration_required F project_supported F newer_renku_available T automated_dockerfile_update T  | NOT POSSIBLE  | METADATA IS AHEAD OF DEPLOYMENT + DOCKERFILE AUTOMATIC MIGRATION             |
| 14 | migration_required F project_supported F newer_renku_available T automated_dockerfile_update F  | NOT POSSIBLE                         | METADATA IS AHEAD OF DEPLOYMENT + MANUAL DOCKERFILE UPDATE                   |
| 15 | migration_required F project_supported F newer_renku_available F automated_dockerfile_update T  | NOT POSSIBLE   | METADATA AHEAD OF DEPLOYMENT + DOCKERFILE UP TO DATE                         |
| 16 | migration_required F project_supported F newer_renku_available F automated_dockerfile_update F  | NOT POSSIBLE    | METADATA AHEAD OF DEPLOYMENT + DOCKERFILE UINKNOWN SINCE IT’S NOT COMPATIBLE |

# Status

- [ ] Step 0: Check that the RP issue behaves as we expect, give feedback (sprint 2021-06-04)
- [ ] Step 1: Update the message without a link to the changelog
- [ ] Step 2: Design change to API to receive link to the changelog
- [ ] Step 3: Add a link to the changelog once the core-service returns it

## Historical

Two situations can happen:

- There is a newer version of renku-python, but the metadata is compatible 
- There is a newer version of renku-python, but the Dockerfile does not support automatic updating

The first is explained below, the second still needs a design.

### Details

In a project like this:
https://virginia.dev.renku.ch/projects/virginiafriedrich/my-test-project-vir/overview/status

We see a message like this:
image

image

## Mockup

image

## 2021-03-30 Update

From @Panaetius:

So you now get back

```
automated_template_update = fields.Boolean()
template_source = fields.String()
template_ref = fields.String()
template_id = fields.String()
```

on the `migrations_check endpoint`. `automated_template_update` is set on a template and determines if that template supports updating or not. if it's false, the service will only update if passed the "force_template_update" flag.

```
template_source = repository or "renku" if it was created with the CLI
template_ref = branch/tag used in the repo or empty
template_id = name of the template, like "python-minimal"
```

### PR DESCRIPTION
**Pull request by vfried**
[Original text has been moved into a comment below]

The UI now handles the new information from the migrations_check endpoint.

To test, look at some project and check that the "Status" page shows the information you expect to see there. Here are a few specific examples:

## Migration possible, but not necessary

https://renku-ci-ui-1422.dev.renku.ch/projects/cr-migration-test/test-1-0-0/overview/status

(n.b. in this case, we should not show a warning sign, but this will be fixed)

image

## Migration necessary, can be done automatically

https://renku-ci-ui-1422.dev.renku.ch/projects/cr-migration-test/test-8

image

## Migration necessary, cannot be done automatically

https://renku-ci-ui-1422.dev.renku.ch/projects/cr-migration-test/test-7/overview/status

image

Closes #1233 

/deploy renku=1.0-next renku-core=v1.0.1 renku-graph=cli-v1

### CODE REVIEW

**Review by ciyer — COMMENTED** [review]
Code looks very good. It is much easier to follow! I still need to test, and will do that when I am back.

**Comment by rokroskar** [comment]
It looks like this logic doesn't quite work correctly? See https://renku-ci-ui-1422.dev.renku.ch/projects/rokroskar/py090/overview/status which uses a template from master of the templates repo from 2 months ago and it should therefore be updated. The response from the service is 

```json
{"result": {"template_source": "https://github.com/SwissDataScienceCenter/renku-project-template", "latest_version": "0.16.2", "template_id": "python-minimal", "latest_template_version": "7598ddf356e28c80747f93ce97a55a69082b5cf1", "automated_template_update": false, "docker_update_possible": false, "project_version": "0.16.2", "template_ref": "master", "current_template_version": "36d1ab1b1a2996c9532095043cdd8ce6779c38c0", "migration_required": false, "project_supported": true, "template_update_possible": true}}
```

**Comment by ciyer** [comment]
**From Virginia**

Renku version status changed to behave like this...

https://github.com/SwissDataScienceCenter/renku-ui/issues/1233#issuecomment-834159960

Logic has been split into three parts:
- Template
- RenkuLab compatibility (metadata)
- Renku Version (docker file related)

Since logic has been split the code was also split into 3 files.  Each file has scenarios that are then used in a switch/case to decide what will be displayed. Errors, loading, etc are not part of this scenarios.

### ProjectVersionStatus

RENKU_VERSION_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED",
  RENKU_UP_TO_DATE: "RENKU_UP_TO_DATE",
  NEW_VERSION_NOT_REQUIRED_AUTO: "NEW_VERSION_NOT_REQUIRED_AUTO", --> new version not required automatic update possible
  NEW_VERSION_REQUIRED_AUTO: "NEW_VERSION_REQUIRED_AUTO", --> new version required automatic update possible
  NEW_VERSION_NOT_REQUIRED_MANUAL: "NEW_VERSION_NOT_REQUIRED_MANUAL", --> new version not required automatic update not possible
  NEW_VERSION_REQUIRED_MANUAL: "NEW_VERSION_REQUIRED_MANUAL" --> new version required automatic update not possible
};


### RenkuLabCompatibilityStatus

RENKULAB_COMPATIBILITY_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED", 
  RENKULAB_UP_TO_DATE: "RENKULAB_UP_TO_DATE",
  NEW_VERSION_SHOW_BUTTON: "NEW_VERSION_SHOW_BUTTON", --> update needed and will be done with renku version
  NEW_VERSION_NO_BUTTON: "NEW_VERSION_NO_BUTTON" --> update needed but an update in renku version not needed, button to update only metadata will be displayed
};

### TemplateVersionStatus

TEMPLATE_VERSION_SCENARIOS = {
  PROJECT_NOT_SUPPORTED: "PROJECT_NOT_SUPPORTED",
  TEMPLATE_NOT_VERSIONED: "TEMPLATE_NOT_VERSIONED", --> template can't be updated
  TEMPLATE_UP_TO_DATE: "TEMPLATE_UP_TO_DATE", --> no update needed
  NEW_TEMPLATE_AUTO: "NEW_TEMPLATE_AUTO",  --> update needed automatic update posible
  NEW_TEMPLATE_MANUAL: "NEW_TEMPLATE_MANUAL" --> update needed automatic update not posible
};


Testing for messages can be done doing something like this.... 

change this
image

for
image

Real testing coming soon :) 

Run telepresence on: https://renku-ci-rp-2122.dev.renku.ch 
A small temporary change on the telepresence file is required to do this on lines 80 and 81 `DEV_NAMESPACE=renku-ci-rp-${PR}`  ` SERVICE_NAME=renku-ci-rp-${PR}-ui`

File: client/src/project/Project.js [hunk 1]
```diff
@@ -214,7 +212,6 @@ class View extends Component {
     const projectData =
       this.projectCoordinator.fetchProject(this.props.client, pathComponents.projectPathWithNamespace);
     projectData.then(data => {
```
Comment (andre-code) [inline client/src/project/Project.js:214]: Once `data` is no longer used I would suggest removing it and instead of `.then` use  `const projectData = await this.projectCoordinator.fetchProject(this.props.client, pathComponents.projectPathWithNamespace);`

**Comment by andre-code** [comment]
Great feature and also refactoring the code for the project model. 👏 
I suggest adding unit tests especially for functions in the MigrationUtils file.
Some projects to test with the expected behavior in the project description (as we did for the project overview suggestion) would be very useful for testing.

File: client/src/model/RenkuModels.js [hunk 2]
```diff
@@ -327,8 +270,9 @@ const projectGlobalSchema = new Schema({
   forkedFromProject: { [Prop.INITIAL]: {} },
   metadata: {
     [Prop.SCHEMA]: new Schema({
-      avatarUrl: { [Prop.INITIAL]: null, [Prop.MANDATORY]: true }, // avatar_url
       accessLevel: { [Prop.INITIAL]: 0, [Prop.MANDATORY]: true }, // visibility.access_level
+      available: { [Prop.INITIAL]: null, [Prop.MANDATORY]: true },
```
[the remark this answers is not in the document]
Comment (ciyer) [reply client/src/model/RenkuModels.js]: I do not completely understand what this is used for, so I removed it. It does not seem to cause any problems.

**Comment by ciyer** [comment]
> Great feature and also refactoring the code for the project model. 👏
I suggest adding unit tests especially for functions in the MigrationUtils file.
Some projects to test for all cases with the expected behavior in the project description (as we did for the project overview suggestion) would be very useful for testing.

Very good suggestions! I have done both of these.

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
The code looks good!
Would it make sense to add a link to the external template repo in the "Template Version --> Template" URL? It would be the props `template_status.template_source`.

Screenshot_20211215_151214

********

I've found just a couple of confusing cases, not 100% sure if it's the UI using the wrong field from the core service or if a wrong value is provided by the service.

This is an example, created from an old template
URL: https://github.com/SwissDataScienceCenter/renku-project-template
REF: 0.1.18

The `Renku version` field says the project is at `1.0.0`, the latest version is the same, but the user can click on update.
Screenshot_20211215_150228

Clicking on it actually makes it disappear, and the change seems to be a bump from dockerfile version 0.14.1 to 1.0.0


Screenshot_20211215_150515

Is it possible that the intended field for `Project Renku Version` is the `dockerfile_renku_version` value?

In this project (https://renku-ci-ui-1422.dev.renku.ch/projects/lorenzo.cavazzi.tech/1-0-0-dev/overview/status ), forked by one of the examples, I see a similar issue.  The project version seems to be showing the template version. From the API, it seems that `dockerfle_renku_version` would be the right field to show

Screenshot_20211215_150624

**Comment by ciyer** [comment]
Good suggestions! I have done what I can to solve these problems. 

1. If the template_source is a link, show it as one + if the there is a template_ref, show it:

image

image


Compare with this project where the template_source is just a string and there is no template_ref:

image

File: client/src/project/status/TemplateVersionStatus.present.js [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+
+}
+
+function TemplateSource({ template_source }) {
+  const components = template_source.split("/");
+  // if there are no '/', then template_source is not a URL
+  if (components.length < 2)
+    return template_source;
+  const lastComponent = components[components.length - 1];
+  return <a href={template_source}>{lastComponent}</a>;
```
Comment (lorenzo-cavazzi) [inline client/src/project/status/TemplateVersionStatus.present.js:114]: Would it make sense to use the `ExternalLink` component here to keep the behavior aligned with the other links? E.G. opening in a new tab

**Review by lorenzo-cavazzi — APPROVED** [review]
Great to see this big PR ready! :tada: 
I added a very minor comment, feel free to ignore it.

In general, I'm wondering if we should enforce more the outdated renku version, since it may create problems in sessions :thinking: 
Anyway, this is something to think about in a separate issue.
Screenshot_20211216_173441
