### PR TITLE
Fix problems with relative links

### LINKED ISSUE #1655: relative links (e.g. images and notebooks) not rendering on renkulab READMEs
## Description

When embedding content (e.g. images, notebooks) in READMEs using relative paths, they are not rendered on renkulab despite being displayed normally on gitlab. Images are rendered normally when using absolute paths (URLs).

This happens both on the normal and dev instances.

## Reproduce

1. Create project
2. Add readme
3. Embed  image with relative path: `image`, or embed notebook with relative path: `[notebook](./notebooks/test.ipynb)

## Examples

* [Fails to render on renkulab.io](https://renkulab.io/projects/renku-stories/digirhythm)
  +  Other examples: [MATLAB](https://renkulab.io/projects/learn-renku/working-with-matlab), [cellpose-napari](https://renkulab.io/projects/cyril.matthey-doret/cellpose-napari), [Desktop](https://renkulab.io/gitlab/learn-renku/renku-desktop/-/blob/master/README.md) where `[Part 3.](./notebooks/desktop-icons.ipynb)` redirects to `Cannot GET /ui-server/projects/learn-renku/renku-desktop/files/blob/notebooks/desktop-icons.ipynb`
* [Also fails  on dev instance](https://renku-ci-ui-1567.dev.renku.ch/projects/cyril.mattheydoret/digirhythm-test)
* [Absolute image paths are rendered normally](https://renkulab.io/projects/learn-renku/teaching-on-renku/autograde)

### PR DESCRIPTION
**Pull request by ciyer**
# Testing

Look at this project 

  https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links

Check that the images and links that should work do, and those that should not do not.

Do the same when viewing the README in the file view:

  https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links/files/blob/README.md

And here is an example in a subfolder.

  https://renku-ci-ui-1673.dev.renku.ch/projects/renku-qa/relative-links/files/blob/subfolder/README.md

Fix #1655 

/deploy renku=1.0-next

### CODE REVIEW

File: client/src/utils/components/markdown/RenkuMarkdownWithPathTranslation.js [hunk 1]
```diff
@@ -223,7 +223,7 @@ function RenkuMarkdownWithPathTranslation(props) {
   }
 
   const previewLinks = divWithMarkdown.getElementsByTagName("a");
-  const fullBaseUrl = props.client.baseUrl.replace("/api", "/projects")
+  const fullBaseUrl = props.client.baseUrl.replace("/ui-server/api", "/projects")
```
Comment (lorenzo-cavazzi) [inline client/src/utils/components/markdown/RenkuMarkdownWithPathTranslation.js:226]:
```suggestion
  const fullBaseUrl = props.client.uiserverUrl.replace("/ui-server", "/projects")
```
Not a big change tbf since "baseUrl" is manually defined as "uiserverUrl" + "/api" :grin: 

Actually, the best solution would be using the `params["BASE_URL"]` variable that contains the pure UI URL. That would be robust to deploying UI and ui-server to different URLs. It sounds confusing, but `client.baseUrl` uses `params["UISERVER_URL"]`

**Review by lorenzo-cavazzi — APPROVED** [review]
Nice fix!

We could also switch to using `params["BASE_URL"]` if we don't want to use `.replace()` anymore. But we can also merge this right away.

File: client/src/utils/components/markdown/RenkuMarkdownWithPathTranslation.js (hunk 1 above)
Comment (ciyer) [reply client/src/utils/components/markdown/RenkuMarkdownWithPathTranslation.js]: Yes, I didn't like that bit of code much either. I switched to using `Url.get(Url.pages.projects)`, which is, I think, an even better solution.

**Review by lorenzo-cavazzi — APPROVED** [review]
