### PR TITLE
refactor: improve modal headers, fix close button position

### LINKED ISSUE #3410: Vertically center the close button in modals
Whenever the modal header content is lengthy, the `X` close button is positioned a little lower and it looks a bit off compared to the expected top-right position. We might want to position the button better.

Hint: the positioning depends on the parent `modal-header` class using `display: flex` and `align-items: center`.

Screenshot_20241126_164702

### PR DESCRIPTION
**Pull request by ciyer**
There are multiple ways these problems can be fixed, but in discussion with @leafty, it seems that the best solution is just to ensure that the modal dialog titles are short, adding further information in their own header blocks.

image

image

image

Fix #3410

/deploy

### CODE REVIEW

File: client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx [hunk 1]
```diff
@@ -92,7 +92,10 @@ export default function ProjectConnectDataConnectorsModal({
         toggle={toggle}
         data-cy="project-data-connector-connect-header"
       >
-        <ProjectConnectDataConnectorModalHeader mode={mode} setMode={setMode} />
+        <ProjectConnectDataConnectorModalTitle />
+      </ModalHeader>
+      <ModalHeader tag="div">
```
Comment (leafty) [inline client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx:97]: It would be better to avoid having another `modal-title`:

```suggestion
      <div className="modal-header">
```

File: client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx [hunk 2]
```diff
@@ -136,54 +133,63 @@ function ProjectConnectDataConnectorModalHeader({
...
 
+function ProjectConnectDataConnectorModeSwitch({
+  mode,
+  setMode,
+}: {
+  mode: ProjectConnectDataConnectorMode;
+  setMode: (mode: ProjectConnectDataConnectorMode) => void;
+}) {
+  return (
+    <div className="mt-3">
```
Comment (leafty) [inline client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx:150]: The margins are weird here:

```suggestion
```

File: client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx [hunk 3]
```diff
@@ -136,54 +133,63 @@ function ProjectConnectDataConnectorModalHeader({
...
+          value="link"
+          checked={mode === "link"}
+          onChange={() => {
+            setMode("link");
+          }}
+        />
+        <Label
+          data-cy="project-data-controller-mode-link"
+          for="project-data-controller-mode-link"
+          className={cx("btn", "btn-outline-primary")}
```
Comment (leafty) [inline client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx:165]:
```suggestion
          className={cx("btn", "btn-outline-primary", "mb-0")}
```

File: client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx [hunk 4]
```diff
@@ -136,54 +133,63 @@ function ProjectConnectDataConnectorModalHeader({
...
+          value="create"
+          checked={mode === "create"}
+          onChange={() => {
+            setMode("create");
+          }}
+        />
+        <Label
+          data-cy="project-data-controller-mode-create"
+          for="project-data-controller-mode-create"
+          className={cx("btn", "btn-outline-primary")}
```
Comment (leafty) [inline client/src/features/ProjectPageV2/ProjectPageContent/DataConnectors/ProjectConnectDataConnectorsModal.tsx:183]:
```suggestion
          className={cx("btn", "btn-outline-primary", "mb-0")}
```

**Review by leafty — COMMENTED** [review]
The code suggestions make the data connector modal look like this:

Screenshot 2025-03-10 at 13 47 22

File: client/src/features/groupsV2/new/GroupNew.tsx [hunk 5]
```diff
@@ -70,10 +70,10 @@ export default function GroupNew() {
...
         toggle={toggleModal}
       >
-        <ModalHeader tag="div" toggle={toggleModal}>
-          <h2>
-            <People className="bi" /> Create a new group
-          </h2>
+        <ModalHeader toggle={toggleModal}>
+          <People className="bi" /> Create a new group
+        </ModalHeader>
+        <ModalHeader tag="div">
```
Comment (leafty) [inline client/src/features/groupsV2/new/GroupNew.tsx:76]: nitpick:

```suggestion
        <div className="modal-header">
```

File: client/src/features/projectsV2/new/ProjectV2New.tsx [hunk 6]
```diff
@@ -73,10 +73,10 @@ export default function ProjectV2New() {
...
         toggle={toggleModal}
       >
-        <ModalHeader tag="div" toggle={toggleModal}>
-          <h2>
-            <Folder className="bi" /> Create a new project
-          </h2>
+        <ModalHeader toggle={toggleModal}>
+          <Folder className="bi" /> Create a new project
+        </ModalHeader>
+        <ModalHeader tag="div">
```
Comment (leafty) [inline client/src/features/projectsV2/new/ProjectV2New.tsx:79]: nitpick:

```suggestion
        <div className="modal-header">
```

**Review by leafty — DISMISSED** [review]
LGTM

File: client/src/components/modal/ModalHeader.tsx [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+ */
+
+import cx from "classnames";
+import { type ModalHeaderProps } from "reactstrap";
+
+interface RenkuModalHeaderProps extends Omit<ModalHeaderProps, "title>"> {
+  title: React.ReactNode;
+}
+
+export default function RenkuModalHeader({
```
Comment (leafty) [inline client/src/components/modal/ModalHeader.tsx:26]: nitpick:
```suggestion
export default function LargeModalHeader({
```

Also, the filename needs to match the component name.

File: client/src/components/modal/ModalHeader.tsx [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+        className={cx(className, "modal-header", children && "border-0")}
+        {...props}
+      >
+        <h1 className={cx("modal-title", "fs-5")}>{title}</h1>
+        <button
+          type="button"
+          className="btn-close"
+          data-bs-dismiss="modal"
+          aria-label="Close"
+        ></button>
```
Comment (leafty) [inline client/src/components/modal/ModalHeader.tsx:44]:
```suggestion
        />
```

File: client/src/components/modal/ModalHeader.tsx
Comment (leafty) [inline client/src/components/modal/ModalHeader.tsx:1]: It seems that this solution does not work; clicking the close icon ("X") does nothing.

**Review by leafty — CHANGES_REQUESTED** [review]
We can check if a working solution can be found because the modal header is broken with this solution.

File: client/src/components/modal/ModalHeader.tsx [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import cx from "classnames";
+import { type ModalHeaderProps as BaseModalHeaderProps } from "reactstrap";
+
+interface ModalHeaderProps extends Omit<BaseModalHeaderProps, "title>"> {
```
Comment (leafty) [inline client/src/components/modal/ModalHeader.tsx:22]: This type is not appropriate: `<div>` (below) cannot take `BaseModalHeaderProps` as props.

The type needs to be:
```tsx
interface ModalHeaderProps extends React.HTMLAttributes<HTMLDivElement> {
  modalTitle: React.ReactNode;
  toggle: BaseModalHeaderProps["toggle"];
}

It is important to not shadow `title` which is an allowed property on `div`.
```

**Review by leafty — APPROVED** [review]
LGTM
