### PR TITLE
fix: prevent duplication of falsy options

### LINKED ISSUE #1122: Default value added to enum options
On https://limited.renku.ch/ , the default value of GPU seems to be added as an extra `0` despite that value being already available in the list of choices.
It's possible that the default value is a `"0"` instead of a `0`, or the other way around.
Double-check the `enum` options

image (2)
image (3)
image (4)

From here: https://swiss-data-science.slack.com/archives/CAJMXA6PQ/p1605257685165200

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Remove the duplication on notebooks options that could be tested to false.
That may happen when receiving the number `0` as one of the possible values.

Screenshot_20210628_152245

**How to test**: This would require a deployment with GPUs. One way to manually fake it would be to add the following code before the `return data;` at line 82 in the file "client/src/api-client/notebook-servers.js" 
```
data = {
  ...data, gpu_request: {
    "default": 0,
    "displayName": "Number of GPUs",
    "options": [
      0,
      1,
      2
    ],
    "order": 5,
    "type": "enum"
  }
};
```

/deploy renku=ui-design-2021
fix #1122

### CODE REVIEW

File: client/src/notebooks/Notebooks.container.js [hunk 1]
```diff
@@ -451,7 +451,7 @@ class StartNotebookServer extends Component {
   setServerOptionFromEvent(option, event, providedValue = null) {
     const target = event.target.type.toLowerCase();
     let value = providedValue;
-    if (!providedValue) {
+    if (!providedValue && providedValue !== 0) {
```
Comment (ciyer) [inline client/src/notebooks/Notebooks.container.js:454]:
```suggestion
    if (!providedValue != null) {
```

I think the logic here is clearer if we test for `null`, especially if we consider, in addition to `providedValue === 0` the possibility of what happens when `providedValue === false`.

**Review by ciyer — CHANGES_REQUESTED** [review]
Behavior looks good! Made a suggestion for the code.

**Review by ciyer — APPROVED** [review]
👍
