### PR TITLE
fix: make custom launch work

### LINKED ISSUE #3689: Custom env variables break custom launches
> most likely, the fix is to rename the `custom` parameter to `renku_custom_launch` so that custom launches work again

### PR DESCRIPTION
**Pull request by leafty**
Closes #3689.

/deploy

### CODE REVIEW

File: client/src/features/sessionsV2/SessionStartPage.tsx [hunk 1]
```diff
@@ -208,10 +209,12 @@ function SessionStarting({ launcher, project }: StartSessionFromLauncherProps) {
       cloudstorage: startSessionOptionsV2.cloudStorage
         ?.filter(({ active }) => active)
         .map((cs) => storageDefinitionFromConfig(cs)),
-      env_variable_overrides: Array.from(searchParams).map(([name, value]) => ({
-        name,
-        value,
-      })),
+      env_variable_overrides: Array.from(searchParams)
+        .filter(([name]) => typeof validateEnvVariableName(name) !== "string")
```
Comment (leafty) [inline client/src/features/sessionsV2/SessionStartPage.tsx:213]:
```suggestion
        .filter(([name]) => typeof validateEnvVariableName(name) === true)
```

File: client/src/features/sessionsV2/SessionStartPage.tsx [hunk 2]
```diff
@@ -208,10 +209,12 @@ function SessionStarting({ launcher, project }: StartSessionFromLauncherProps) {
       cloudstorage: startSessionOptionsV2.cloudStorage
         ?.filter(({ active }) => active)
         .map((cs) => storageDefinitionFromConfig(cs)),
-      env_variable_overrides: Array.from(searchParams).map(([name, value]) => ({
-        name,
-        value,
-      })),
+      env_variable_overrides: Array.from(searchParams)
+        .filter(([name]) => typeof validateEnvVariableName(name) === true)
```
Comment (leafty) [inline client/src/features/sessionsV2/SessionStartPage.tsx:213]:
```suggestion
        .filter(([name]) => validateEnvVariableName(name) === true)
```
