### PR TITLE
fix: hide the edit button when the user does not have permissions

### LINKED ISSUE #3446: Do not show the edit buttons and the Settings tab in projects and groups
This is only sometimes consistent.

We should remove the buttons to add/modify resources on projects/groups. That includes:

- Adding resources (repositories, data, sessions, ...)
- Editing (info)
- ~Settings page (redirect if needed)~ [EDIT: let the Settings section be visible to everyone]

--- EDIT ---

Places where we still show edit buttons despite no write access:

- Project info box
- Code repo listing
- Maybe also data connectors - need to be checked
- code repo side sheet top right edit button
- data connector side sheet top right edit button
- session launcher + environment side sheet buttons (top right, environment, and resource class)

---

Example - Code Repository:
image

### PR DESCRIPTION
**Pull request by leafty**
Closes #3446.

Update the actions buttons on the project / group / user pages to be presented only when the corresponding action is available to the user.

## Project Page - Code Repositories

**Can edit project**
image

**Cannot edit project**
Screenshot 2024-12-20 at 11 44 48

## Project Page - Sessions

**Can edit project**
image

**Cannot edit project**
image

## Project Page - Data Connectors

**Can edit data connector & Can edit project**
image

**Can edit data connector & Cannot edit project**
Screenshot 2024-12-20 at 11 48 48

**Cannot edit data connector & Can edit project**
image

**Cannot edit data connector & Cannot edit project**
image

**Anonymous user (cannot save credentials)**
image

## Group or User Page - Data Connectors

**Can delete data connector (owner)**
image

**Can edit data connector**
image

**Cannot edit data connector**
image

**Anonymous user (cannot save credentials)**
image

/deploy

### CODE REVIEW

File: client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx [hunk 1]
```diff
@@ -359,15 +362,26 @@ function DataConnectorRemoveUnlinkModal({
...
+  const projectPermissions = useProjectPermissions({
+    projectId: projectId ?? "",
+  });
+
+  //   const { data: project, isLoading: isLoadingProject } =
+  //   useGetNamespacesByNamespaceProjectsAndSlugQuery({
+  //     namespace: projectNamespace,
+  //     slug: projectSlug,
+  //   });
+  // const permissions = useProjectPermissions({ projectId: project?.id ?? "" });
```
Comment (lorenzo-cavazzi) [inline client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx:383]: Leftover?

**Review by lorenzo-cavazzi — APPROVED** [review]
Lgtm! :rocket:

File: client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx (hunk 1 above)
Comment (leafty) [reply client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx:383]: Yes

Comment (leafty) [inline client/src/features/dataConnectorsV2/components/DataConnectorActions.tsx:383]:
```suggestion
```

**Review by lorenzo-cavazzi — APPROVED** [review]
